before_script:
  - virtualenv testrunner
  - source testrunner/bin/activate
  - which python
  - python -v
  - pip install numpy
  - pip install scipy
  - python setup.py install

test:
  script:
    - python tests/test_job.py